### ISSUE TITLE
Pregledanje rada

### ISSUE THREAD

**Issue by Milicak93** [MATF-RG17/RG013-speedracing#1]
Zavrsila sam igricu onako kako je zamisljena. Molim Vas pogledajte, proverite da li sve radi i javite ukoliko treba da menjam nesto.
Hvala!

**Comment by ivan-cukic-matf** [comment]
Otvorite ovaj issue ponovo kad zavrsite sa #2 i #3

**Comment by Milicak93** [comment]
Uradila sam taskove #2 i #3. Kada stignete, molim Vas pregledajte i javite da li je ok. Hvala!

**Comment by ivan-cukic-matf** [comment]
Deluje u redu. Mislim da necu imati vise zamerki.
