### ISSUE TITLE
Razdvojite na vise funkcija

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG013-speedracing#2]
Razdvojite `on_display` na vise funkcija - iscrtavanje svakog objekta da bude odvojena f-ja.

https://github.com/MATF-RG17/RG013-speedracing/blob/65b1215b56c5f30d6cca3f360f1877b0136b48a3/main.c#L460

**Comment by Milicak93** [comment]
Razdvojila sam funkcije, posebne su funkcije crtanja sasije, tockova, stakla, puta, traka pored puta, startne linije i trave. Ostavila sam iscrtavanje teksta jedino u funkciji on_display, nadam se da je to ok.
