### ISSUE TITLE
1st person

### ISSUE THREAD

**Issue by ivan-cukic-matf** [MATF-RG17/RG013-speedracing#3]
Dodajte 1st person poziciju kamere (ne morate da crtate kontrolnu tablu automobila ili bilo sta slicno - samo da se kamera nalazi _na_ sofersajbni.

Bilo bi super ako bi prelazak izmedju modova 1st i 3rd person bio animiran - da kamera ne skoci sa jednog mesta na drugo, nego da je kretanje kamere animirano.

**Comment by Milicak93** [comment]
Dodala sam 1st person cameru, kao i tranziciju. Potrudila sam se da kod detaljno iskomentarisem, ali ako je potrebno jos obrazlozenja, slobodno napisite.
